name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.event_name == "push" && github.ref == "refs/heads/main"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t my-image .

      - name: Push Docker image
        run: docker tag my-image ${{ secrets.DOCKERHUB_USERNAME }}/my-image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image
